# fly.toml app configuration file generated for vis-sendnotes on 2023-12-16T15:02:01-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vis-sendnotes"
primary_region = "ord"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.3"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "pgsql"
  APP_URL = " https://vis-sendnotes.fly.dev/"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
